### ISSUE TITLE
项目运行时出现问题

### ISSUE THREAD

**Issue by Sparxzzh** [HYPJUDY/movie-ticket-and-service-website#11]
大佬您好，本人小白蒟蒻一枚，在运行此项目的时候出现以下问题，
![TIM图片20200425153236](https://user-images.githubusercontent.com/39088991/80274077-7163a580-870a-11ea-8ebb-0c0f4f5af44f.png)
![TIM图片20200425153401](https://user-images.githubusercontent.com/39088991/80274078-73c5ff80-870a-11ea-8cd6-d2769c809867.png)
![TIM图片20200425153430](https://user-images.githubusercontent.com/39088991/80274081-758fc300-870a-11ea-8b62-c6e9d41f09c2.png)
希望大佬能够抽出宝贵的时间帮助解决一下！！不胜感激

**Comment by HYPJUDY** [comment]
你好，运行出现问题可能是因为依赖环境版本的变迁，抱歉这个repo时间太久远已经不再维护代码细节了。这个[博文](https://hypjudy.github.io/2017/05/30/spring-boot-web-application/)里提及了一些安装和运行的条件及参考的链接，请看看能不能解决你的问题。

**Comment by Sparxzzh** [comment]
ok 感谢回复！
